
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Aruba-1965', 'Aruba', 'ABW', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Afghanistan-1965', 'Afghanistan', 'AFG', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '1006666637');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Angola-1965', 'Angola', 'AGO', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Albania-1965', 'Albania', 'ALB', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Andorra-1965', 'Andorra', 'AND', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Arab World-1965', 'Arab World', 'ARB', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('United Arab Emirates-1965', 'United Arab Emirates', 'ARE', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Argentina-1965', 'Argentina', 'ARG', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '28344705966');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Armenia-1965', 'Armenia', 'ARM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('American Samoa-1965', 'American Samoa', 'ASM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Antigua and Barbuda-1965', 'Antigua and Barbuda', 'ATG', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Australia-1965', 'Australia', 'AUS', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '25936835031');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Austria-1965', 'Austria', 'AUT', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '9994070615');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Azerbaijan-1965', 'Azerbaijan', 'AZE', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Burundi-1965', 'Burundi', 'BDI', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '158994962');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Belgium-1965', 'Belgium', 'BEL', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '17371457607');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Benin-1965', 'Benin', 'BEN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '289908720');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Burkina Faso-1965', 'Burkina Faso', 'BFA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '422916848');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Bangladesh-1965', 'Bangladesh', 'BGD', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '5906636557');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Bulgaria-1965', 'Bulgaria', 'BGR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Bahrain-1965', 'Bahrain', 'BHR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Bahamas-1965', 'Bahamas', 'BHS', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '300392156');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Bosnia and Herzegovina-1965', 'Bosnia and Herzegovina', 'BIH', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Belarus-1965', 'Belarus', 'BLR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Belize-1965', 'Belize', 'BLZ', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '40069930');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Bermuda-1965', 'Bermuda', 'BMU', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '114339048');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Bolivia-1965', 'Bolivia', 'BOL', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '604377104');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Brazil-1965', 'Brazil', 'BRA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '21790035117');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Barbados-1965', 'Barbados', 'BRB', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Brunei Darussalam-1965', 'Brunei Darussalam', 'BRN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '114040245');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Bhutan-1965', 'Bhutan', 'BTN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Botswana-1965', 'Botswana', 'BWA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '45790869');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Central African Republic-1965', 'Central African Republic', 'CAF', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '150574816');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Canada-1965', 'Canada', 'CAN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '54515179580');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Central Europe and the Baltics-1965', 'Central Europe and the Baltics', 'CEB', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Switzerland-1965', 'Switzerland', 'CHE', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '15346741669');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Channel Islands-1965', 'Channel Islands', 'CHI', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Chile-1965', 'Chile', 'CHL', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '6026593750');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('China-1965', 'China', 'CHN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '70436266146');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Cote d\'Ivoire-1965', 'Cote d\'Ivoire', 'CIV', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '919771356');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Cameroon-1965', 'Cameroon', 'CMR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '814139855');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Congo-1965', 'Congo', 'COD', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '4043901818');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Congo-1965', 'Congo', 'COG', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '198318063');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Colombia-1965', 'Colombia', 'COL', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '5760761904');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Comoros-1965', 'Comoros', 'COM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Cabo Verde-1965', 'Cabo Verde', 'CPV', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Costa Rica-1965', 'Costa Rica', 'CRI', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '592981162');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Caribbean small states-1965', 'Caribbean small states', 'CSS', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '2660946063');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Cuba-1965', 'Cuba', 'CUB', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Curacao-1965', 'Curacao', 'CUW', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Cayman Islands-1965', 'Cayman Islands', 'CYM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Cyprus-1965', 'Cyprus', 'CYP', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Czech Republic-1965', 'Czech Republic', 'CZE', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Germany-1965', 'Germany', 'DEU', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Djibouti-1965', 'Djibouti', 'DJI', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Dominica-1965', 'Dominica', 'DMA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Denmark-1965', 'Denmark', 'DNK', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Dominican Republic-1965', 'Dominican Republic', 'DOM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '888100000');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Algeria-1965', 'Algeria', 'DZA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '3136258896');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('East Asia & Pacific (excluding high income)-1965', 'East Asia & Pacific (excluding high income)', 'EAP', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '94581254563');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Early-demographic dividend-1965', 'Early-demographic dividend', 'EAR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '209371590635');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('East Asia & Pacific-1965', 'East Asia & Pacific', 'EAS', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '224575551901');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Europe & Central Asia (excluding high income)-1965', 'Europe & Central Asia (excluding high income)', 'ECA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Europe & Central Asia-1965', 'Europe & Central Asia', 'ECS', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Ecuador-1965', 'Ecuador', 'ECU', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '2387048255');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Egypt-1965', 'Egypt', 'EGY', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '4948667540');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Euro area-1965', 'Euro area', 'EMU', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '407845696622');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Eritrea-1965', 'Eritrea', 'ERI', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Spain-1965', 'Spain', 'ESP', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '24756958694');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Estonia-1965', 'Estonia', 'EST', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Ethiopia-1965', 'Ethiopia', 'ETH', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('European Union-1965', 'European Union', 'EUU', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Fragile and conflict affected situations-1965', 'Fragile and conflict affected situations', 'FCS', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '22034941960');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Finland-1965', 'Finland', 'FIN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '8589340019');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Fiji-1965', 'Fiji', 'FJI', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '147084750');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('France-1965', 'France', 'FRA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '101537248148');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Faroe Islands-1965', 'Faroe Islands', 'FRO', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Micronesia-1965', 'Micronesia', 'FSM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Gabon-1965', 'Gabon', 'GAB', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '226474285');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('United Kingdom-1965', 'United Kingdom', 'GBR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '101824755078');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Georgia-1965', 'Georgia', 'GEO', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Ghana-1965', 'Ghana', 'GHA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '2053462872');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Gibraltar-1965', 'Gibraltar', 'GIB', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Guinea-1965', 'Guinea', 'GIN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Gambia-1965', 'Gambia', 'GMB', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Guinea-Bissau-1965', 'Guinea-Bissau', 'GNB', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Equatorial Guinea-1965', 'Equatorial Guinea', 'GNQ', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '64748333');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Greece-1965', 'Greece', 'GRC', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '7689154053');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Grenada-1965', 'Grenada', 'GRD', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Greenland-1965', 'Greenland', 'GRL', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Guatemala-1965', 'Guatemala', 'GTM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '1331399900');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Guam-1965', 'Guam', 'GUM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Guyana-1965', 'Guyana', 'GUY', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '213235294');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('High income-1965', 'High income', 'HIC', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '1550792874026');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Hong Kong China-1965', 'Hong Kong China', 'HKG', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '2435078534');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Honduras-1965', 'Honduras', 'HND', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '508650000');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Heavily indebted poor countries (HIPC)-1965', 'Heavily indebted poor countries (HIPC)', 'HPC', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '24380468450');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Croatia-1965', 'Croatia', 'HRV', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Haiti-1965', 'Haiti', 'HTI', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '353251800');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Hungary-1965', 'Hungary', 'HUN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('IBRD only-1965', 'IBRD only', 'IBD', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '401064461680');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('IDA & IBRD total-1965', 'IDA & IBRD total', 'IBT', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '454165650874');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('IDA total-1965', 'IDA total', 'IDA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '53602178177');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('IDA blend-1965', 'IDA blend', 'IDB', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '17328250572');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Indonesia-1965', 'Indonesia', 'IDN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('IDA only-1965', 'IDA only', 'IDX', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '37694453113');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Isle of Man-1965', 'Isle of Man', 'IMN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('India-1965', 'India', 'IND', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '59554854574');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Not classified-1965', 'Not classified', 'INX', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Ireland-1965', 'Ireland', 'IRL', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '2945704142');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Iran-1965', 'Iran', 'IRN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '6197319929');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Iraq-1965', 'Iraq', 'IRQ', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Iceland-1965', 'Iceland', 'ISL', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '523694949');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Israel-1965', 'Israel', 'ISR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '3663333333');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Italy-1965', 'Italy', 'ITA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '67978153850');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Jamaica-1965', 'Jamaica', 'JAM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '972140557');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Jordan-1965', 'Jordan', 'JOR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '599831979');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Japan-1965', 'Japan', 'JPN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '90950278257');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Kazakhstan-1965', 'Kazakhstan', 'KAZ', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Kenya-1965', 'Kenya', 'KEN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '997919319');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Kyrgyz Republic-1965', 'Kyrgyz Republic', 'KGZ', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Cambodia-1965', 'Cambodia', 'KHM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '868571428');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Kiribati-1965', 'Kiribati', 'KIR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('St. Kitts and Nevis-1965', 'St. Kitts and Nevis', 'KNA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '13593932');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Korea-1965', 'Korea', 'KOR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '3120833333');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Kuwait-1965', 'Kuwait', 'KWT', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '2097451694');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Latin America & Caribbean (excluding high income)-1965', 'Latin America & Caribbean (excluding high income)', 'LAC', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '105189609504');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Lao PDR-1965', 'Lao PDR', 'LAO', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Lebanon-1965', 'Lebanon', 'LBN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Liberia-1965', 'Liberia', 'LBR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Libya-1965', 'Libya', 'LBY', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('St. Lucia-1965', 'St. Lucia', 'LCA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Latin America & Caribbean-1965', 'Latin America & Caribbean', 'LCN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '118563293437');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Least developed countries: UN classification-1965', 'Least developed countries: UN classification', 'LDC', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Low income-1965', 'Low income', 'LIC', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Liechtenstein-1965', 'Liechtenstein', 'LIE', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Sri Lanka-1965', 'Sri Lanka', 'LKA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '1698319327');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Lower middle income-1965', 'Lower middle income', 'LMC', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '131176268028');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Low & middle income-1965', 'Low & middle income', 'LMY', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '432947252588');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Lesotho-1965', 'Lesotho', 'LSO', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '54878902');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Late-demographic dividend-1965', 'Late-demographic dividend', 'LTE', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '236617311165');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Lithuania-1965', 'Lithuania', 'LTU', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Luxembourg-1965', 'Luxembourg', 'LUX', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '921600736');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Latvia-1965', 'Latvia', 'LVA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Macao China-1965', 'Macao China', 'MAC', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('St. Martin (French part)-1965', 'St. Martin (French part)', 'MAF', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Morocco-1965', 'Morocco', 'MAR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '2948325264');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Monaco-1965', 'Monaco', 'MCO', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Moldova-1965', 'Moldova', 'MDA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Madagascar-1965', 'Madagascar', 'MDG', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '833563472');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Maldives-1965', 'Maldives', 'MDV', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Middle East & North Africa-1965', 'Middle East & North Africa', 'MEA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Mexico-1965', 'Mexico', 'MEX', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '21840000000');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Marshall Islands-1965', 'Marshall Islands', 'MHL', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Middle income-1965', 'Middle income', 'MIC', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '415008741502');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('North Macedonia-1965', 'North Macedonia', 'MKD', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Mali-1965', 'Mali', 'MLI', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Malta-1965', 'Malta', 'MLT', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Myanmar-1965', 'Myanmar', 'MMR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Middle East & North Africa (excluding high income)-1965', 'Middle East & North Africa (excluding high income)', 'MNA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Montenegro-1965', 'Montenegro', 'MNE', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Mongolia-1965', 'Mongolia', 'MNG', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Northern Mariana Islands-1965', 'Northern Mariana Islands', 'MNP', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Mozambique-1965', 'Mozambique', 'MOZ', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Mauritania-1965', 'Mauritania', 'MRT', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '255340526');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Mauritius-1965', 'Mauritius', 'MUS', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Malawi-1965', 'Malawi', 'MWI', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '229455410');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Malaysia-1965', 'Malaysia', 'MYS', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '2956356984');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('North America-1965', 'North America', 'NAC', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '798329518629');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Namibia-1965', 'Namibia', 'NAM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('New Caledonia-1965', 'New Caledonia', 'NCL', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '159594493');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Niger-1965', 'Niger', 'NER', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '673383604');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Nigeria-1965', 'Nigeria', 'NGA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '5874422511');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Nicaragua-1965', 'Nicaragua', 'NIC', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '566542872');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Netherlands-1965', 'Netherlands', 'NLD', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '21000586933');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Norway-1965', 'Norway', 'NOR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '8058681060');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Nepal-1965', 'Nepal', 'NPL', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '735267082');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Nauru-1965', 'Nauru', 'NRU', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('New Zealand-1965', 'New Zealand', 'NZL', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '5654463586');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('OECD members-1965', 'OECD members', 'OED', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '1557930975997');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Oman-1965', 'Oman', 'OMN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '63287594');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Other small states-1965', 'Other small states', 'OSS', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Pakistan-1965', 'Pakistan', 'PAK', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '5929231415');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Panama-1965', 'Panama', 'PAN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '852485300');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Peru-1965', 'Peru', 'PER', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '5166861068');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Philippines-1965', 'Philippines', 'PHL', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '5784398976');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Palau-1965', 'Palau', 'PLW', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Papua New Guinea-1965', 'Papua New Guinea', 'PNG', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '344159480');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Poland-1965', 'Poland', 'POL', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Pre-demographic dividend-1965', 'Pre-demographic dividend', 'PRE', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '15501370622');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Puerto Rico-1965', 'Puerto Rico', 'PRI', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '2881500000');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Korea-1965', 'Korea', 'PRK', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Portugal-1965', 'Portugal', 'PRT', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '4687464054');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Paraguay-1965', 'Paraguay', 'PRY', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '443587301');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('West Bank and Gaza-1965', 'West Bank and Gaza', 'PSE', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Pacific island small states-1965', 'Pacific island small states', 'PSS', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Post-demographic dividend-1965', 'Post-demographic dividend', 'PST', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '1519391440804');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('French Polynesia-1965', 'French Polynesia', 'PYF', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '176534589');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Qatar-1965', 'Qatar', 'QAT', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Romania-1965', 'Romania', 'ROU', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Russian Federation-1965', 'Russian Federation', 'RUS', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Rwanda-1965', 'Rwanda', 'RWA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '148799980');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('South Asia-1965', 'South Asia', 'SAS', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '74298708606');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Saudi Arabia-1965', 'Saudi Arabia', 'SAU', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Sudan-1965', 'Sudan', 'SDN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '1679333333');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Senegal-1965', 'Senegal', 'SEN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '1210058396');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Singapore-1965', 'Singapore', 'SGP', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '974650463');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Solomon Islands-1965', 'Solomon Islands', 'SLB', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Sierra Leone-1965', 'Sierra Leone', 'SLE', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '359379856');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('El Salvador-1965', 'El Salvador', 'SLV', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '877720000');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('San Marino-1965', 'San Marino', 'SMR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Somalia-1965', 'Somalia', 'SOM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '243724533');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Serbia-1965', 'Serbia', 'SRB', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Sub-Saharan Africa (excluding high income)-1965', 'Sub-Saharan Africa (excluding high income)', 'SSA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '41763183885');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('South Sudan-1965', 'South Sudan', 'SSD', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Sub-Saharan Africa-1965', 'Sub-Saharan Africa', 'SSF', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '41973341059');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Small states-1965', 'Small states', 'SST', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Sao Tome and Principe-1965', 'Sao Tome and Principe', 'STP', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Suriname-1965', 'Suriname', 'SUR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '154150000');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Slovak Republic-1965', 'Slovak Republic', 'SVK', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Slovenia-1965', 'Slovenia', 'SVN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Sweden-1965', 'Sweden', 'SWE', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '24795499685');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Eswatini-1965', 'Eswatini', 'SWZ', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '70278594');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Sint Maarten (Dutch part)-1965', 'Sint Maarten (Dutch part)', 'SXM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Seychelles-1965', 'Seychelles', 'SYC', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '15603032');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Syrian Arab Republic-1965', 'Syrian Arab Republic', 'SYR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '1472036550');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Turks and Caicos Islands-1965', 'Turks and Caicos Islands', 'TCA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Chad-1965', 'Chad', 'TCD', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '416926302');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('East Asia & Pacific (IDA & IBRD countries)-1965', 'East Asia & Pacific (IDA & IBRD countries)', 'TEA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '94386870181');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Europe & Central Asia (IDA & IBRD countries)-1965', 'Europe & Central Asia (IDA & IBRD countries)', 'TEC', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Togo-1965', 'Togo', 'TGO', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '187300336');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Thailand-1965', 'Thailand', 'THA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '4388937649');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Tajikistan-1965', 'Tajikistan', 'TJK', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Turkmenistan-1965', 'Turkmenistan', 'TKM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Latin America & the Caribbean (IDA & IBRD countries)-1965', 'Latin America & the Caribbean (IDA & IBRD countries)', 'TLA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '110871922979');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Timor-Leste-1965', 'Timor-Leste', 'TLS', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Middle East & North Africa (IDA & IBRD countries)-1965', 'Middle East & North Africa (IDA & IBRD countries)', 'TMN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Tonga-1965', 'Tonga', 'TON', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('South Asia (IDA & IBRD)-1965', 'South Asia (IDA & IBRD)', 'TSA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '74298708606');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Sub-Saharan Africa (IDA & IBRD countries)-1965', 'Sub-Saharan Africa (IDA & IBRD countries)', 'TSS', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '41973341059');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Trinidad and Tobago-1965', 'Trinidad and Tobago', 'TTO', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '736568861');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Tunisia-1965', 'Tunisia', 'TUN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '991047619');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Turkey-1965', 'Turkey', 'TUR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '11966666666');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Tuvalu-1965', 'Tuvalu', 'TUV', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Tanzania-1965', 'Tanzania', 'TZA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Uganda-1965', 'Uganda', 'UGA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '884873949');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Ukraine-1965', 'Ukraine', 'UKR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Upper middle income-1965', 'Upper middle income', 'UMC', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '281617106855');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Uruguay-1965', 'Uruguay', 'URY', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '1890769326');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('United States-1965', 'United States', 'USA', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '744000000000');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Uzbekistan-1965', 'Uzbekistan', 'UZB', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('St. Vincent and the Grenadines-1965', 'St. Vincent and the Grenadines', 'VCT', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '15108207');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Venezuela-1965', 'Venezuela', 'VEN', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '8427777777');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('British Virgin Islands-1965', 'British Virgin Islands', 'VGB', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Virgin Islands (U.S.)-1965', 'Virgin Islands (U.S.)', 'VIR', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Vietnam-1965', 'Vietnam', 'VNM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Vanuatu-1965', 'Vanuatu', 'VUT', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('World-1965', 'World', 'WLD', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '1966277080224');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Samoa-1965', 'Samoa', 'WSM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Kosovo-1965', 'Kosovo', 'XKX', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Yemen-1965', 'Yemen', 'YEM', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('South Africa-1965', 'South Africa', 'ZAF', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '11334395470');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Zambia-1965', 'Zambia', 'ZMB', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '1082857142');
INSERT INTO gdp_1965 (id, Entity, Code, Indicator_Name, Indicator_Code, gdp_in_1965) VALUES ('Zimbabwe-1965', 'Zimbabwe', 'ZWE', 'GDP (current US$)', 'NY.GDP.MKTP.CD', '1311435800');
